language: nix

matrix:
  fast_finish: true
  include:
    - env: GHCVER=ghc742
    - env: GHCVER=ghc763
    - env: GHCVER=ghc783
    - env: GHCVER=ghc784
    - env: GHCVER=ghc7102
    - env: GHCVER=ghc7103
    - env: GHCVER=ghc801
    - env: GHCVER=ghc802
    - env: GHCVER=ghcHEAD
  allow_failures:
    - env: GHCVER=ghc742
    - env: GHCVER=ghc763
    - env: GHCVER=ghc783
    - env: GHCVER=ghc784
    - env: GHCVER=ghc7102
    - env: GHCVER=ghc7103
    - env: GHCVER=ghcHEAD

before_install:
 - nix-channel --list
 - nix-channel --update

script:
 - nix-build -A acid-state --argstr compiler $GHCVER
